version: '3'
services:
  primary:
    image: postgres:14.5
    restart: always
    command: -c 'config_file=/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5462:5432
    volumes:
      - ./containers/db_primary/data:/var/lib/postgresql/data
      - ./containers/db_primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./containers/db_primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./containers/db_primary/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: pg_isready -d db
      interval: 1s
      timeout: 1s
      retries: 5

  replica:
    image: postgres:14.5
    restart: always
    entrypoint: /entrypoint.sh
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5463:5432
    volumes:
      - ./containers/db_replica/data:/var/lib/postgresql/data
      - ./containers/db_replica/entrypoint.sh:/entrypoint.sh
      - ./containers/db_replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./containers/db_replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: pg_isready -d db
      interval: 1s
      timeout: 1s
      retries: 5
